services:
  - type: web
    name: voicemail-translate
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SENDGRID_API_KEY
        sync: false
      - key: EMAIL_FROM
        value: voicemail@yourdomain.com
      - key: DEFAULT_EMAIL_RECIPIENT
        sync: false
