services:
  - type: web
    name: voicemail-translate
    env: php
    plan: free
    buildCommand: echo "No build needed"
    startCommand: php -S 0.0.0.0:$PORT
    envVars:
      - key: SENDGRID_API_KEY
        sync: false
      - key: EMAIL_FROM
        value: voicemail@yourdomain.com
      - key: DEFAULT_EMAIL_RECIPIENT
        sync: false
